const THREE_COLOURS = {
    NODE: "#FF0000",
    NODE_SELECTED: "#0000FF",
    NODE_MOVEABLE: "#33FF77",
    ELEMENT: "#FF33CC",
    ELEMENT_SELECTED: "#369F2A",
    LINKBAR: "#FFFF00",
    SCENE_BACKGROUND: "#CCFFFF"
}

export default THREE_COLOURS